platform: openshift
namespace: yanko4abhay-dev
replicaCount: 2

image:
  frontend:
    repository: abhayshrivastava/jk-frontend-app
    tag: latest
  backend:
    repository: abhayshrivastava/jk-backend-app
    tag: latest
  db: postgres

service:
  backendPort: 30500
  frontendPort: 30080
  dbPort: 5432

config:
  dbName: mydb
  dbHost: postgres-service
  dbPort: "5432"

secret:
  dbUser: postgres
  dbPassword: password

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "150m"
